INSERT INTO land_uses (land_use_id, name, intensity) VALUES (1, 'Agricultual-Aquaculture', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (2, 'Agricultural-Bush fruit and berries', 0.66);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (3, 'Agricultural-Close Grown Crop', 0.66);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (4, 'Agricultural-Fallow/Idle Cropland', 0.33);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (5, 'Agricultural-Orchard', 0.66);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (6, 'Agricultural-Pasture and Hayland', 0.33);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (7, 'Agricultural-Row Crop', 0.66);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (8, 'Agricultural-Row Crop-Close Grown Crop', 0.66);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (9, 'Agricultural-Vineyard', 0.66);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (10, 'Agricultural-Wheat', 0.66);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (11, 'Agriculture-Cultivated Crops and Irrigated Agriculture', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (12, 'Agriculture-Pasture and Hay', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (13, 'Alder Shrubland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (14, 'Alpine Dwarf-Shrubland, Fell-field and Meadow', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (15, 'Alpine-Subalpine Barrens', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (16, 'Aspen Forest, Woodland, and Parkland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (17, 'Aspen-Birch Forest', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (18, 'Aspen-Mixed Conifer Forest and Woodland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (19, 'Atlantic Coastal Marsh', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (20, 'Atlantic Dunes and Grasslands', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (21, 'Atlantic Swamp Forests', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (22, 'Avalanche Slope Shrubland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (23, 'Balsam Poplar-Aspen Woodland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (24, 'Barren', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (25, 'Beach Meadow', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (26, 'Bedrock, Scree, and Talus', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (27, 'Beech-Maple-Basswood Forest', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (28, 'Big Sagebrush Shrubland and Steppe', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (29, 'Bigtooth Maple Woodland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (30, 'Birch-Aspen Forest', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (31, 'Birch-Cottonwood-Poplar Forest', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (32, 'Black Oak Woodland and Savanna', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (33, 'Black Spruce Forest and Woodland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (34, 'Blackbrush Shrubland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (35, 'Boreal Grassland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (36, 'Bur Oak Woodland and Savanna', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (37, 'California Mixed Evergreen Forest and Woodland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (38, 'Caribbean Deciduous Forest', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (39, 'Caribbean Evergreen Forest', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (40, 'Caribbean Forested Wetland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (41, 'Caribbean Mangrove Forest', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (42, 'Caribbean Mixed Evergreen Deciduous Forest', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (43, 'Caribbean Shrub/Herbaceous Wetland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (44, 'Chaparral', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (45, 'Chestnut Oak Forest and Woodland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (46, 'Chestnut Oak-Virginia Pine Forest and Woodland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (47, 'Coastal Plain Oak Forest', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (48, 'Conifer-Oak Forest and Woodland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (49, 'Creosotebush Desert Scrub', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (50, 'Cypress', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (51, 'Deciduous Shrubland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (52, 'Depressional Wetland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (53, 'Desert Scrub', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (54, 'Developed-General', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (55, 'Developed-High intensity', 1);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (56, 'Developed-Low intensity', 1);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (57, 'Developed-Medium intensity', 1);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (58, 'Developed-Open Space', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (59, 'Developed-Roads', 1);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (60, 'Developed-Upland Deciduous Forest', 1);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (61, 'Developed-Upland Evergreen Forest', 1);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (62, 'Developed-Upland Herbaceous', 1);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (63, 'Developed-Upland Mixed Forest', 1);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (64, 'Developed-Upland Shrubland', 1);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (65, 'Douglas-fir Forest and Woodland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (66, 'Douglas-fir-Grand Fir-White Fir Forest and Woodland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (67, 'Douglas-fir-Ponderosa Pine-Lodgepole Pine Forest and Woodland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (68, 'Douglas-fir-Western Hemlock Forest and Woodland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (69, 'Dry Aspen-Steppe Bluff', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (70, 'Dry Tundra', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (71, 'Dune Grassland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (72, 'Dwarf Shrubland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (73, 'Eastern Floodplain Forests', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (74, 'Eastern Small Stream Riparian Forests', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (75, 'Floodplain Forest and Shrubland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (76, 'Freshwater Aquatic Bed', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (77, 'Freshwater Marsh', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (78, 'Glades and Barrens', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (79, 'Grassland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (80, 'Grassland and Steppe', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (81, 'Greasewood Shrubland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (82, 'Great Lakes Alvar', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (83, 'Hammocks', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (84, 'Hardwood Flatwoods', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (85, 'Hawai''i Dry Forest', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (86, 'Hawai''i Dry Grassland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (87, 'Hawai''i Dry Shrubland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (88, 'Hawai''i Mesic Forest', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (89, 'Hawai''i Mesic Grassland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (90, 'Hawai''i Mesic Shrubland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (91, 'Hawai''i Rainforest', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (92, 'Heathland and Grassland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (93, 'Herbaceous Meadow', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (94, 'Inland Marshes and Prairies', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (95, 'Introduced Annual Grassland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (96, 'Introduced Annual and Biennial Forbland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (97, 'Introduced Herbaceous Wetland Vegetation', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (98, 'Introduced Perennial Grassland and Forbland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (99, 'Introduced Riparian Vegetation', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (100, 'Introduced Upland Vegetation-Shrub', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (101, 'Introduced Upland Vegetation-Treed', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (102, 'Introduced Wetland Vegetation', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (103, 'Introduced Woody Wetland Vegetation', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (104, 'Jack Pine Forest', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (105, 'Juniper Woodland and Savanna', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (106, 'Juniper-Oak', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (107, 'Limber Pine Woodland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (108, 'Loblolly Pine Forest and Woodland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (109, 'Loblolly Pine-Slash Pine Forest and Woodland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (110, 'Lodgepole Pine Forest and Woodland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (111, 'Longleaf Pine Woodland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (112, 'Low Sagebrush Shrubland and Steppe', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (113, 'Managed Tree Plantation', 0.66);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (114, 'Mangrove', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (115, 'Maritime Forest', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (116, 'Mesquite Woodland and Scrub', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (117, 'Mixedgrass Prairie', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (118, 'Modified-Managed Prairie Grassland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (119, 'Montane Oak Forest', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (120, 'Mountain Hemlock Forest and Woodland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (121, 'Mountain Mahogany Woodland and Shrubland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (122, 'Nodata', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (123, 'Open Water', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (124, 'Pacific Coastal Marsh', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (125, 'Pacific Coastal Scrub', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (126, 'Pacific Islands Limestone Forest', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (127, 'Pacific Islands Littoral/Strand Vegetation', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (128, 'Pacific Islands Lowland Forest', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (129, 'Pacific Islands Mangrove Forest', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (130, 'Pacific Islands Palm Forest', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (131, 'Pacific Islands Ravine Forest', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (132, 'Pacific Islands Savannah', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (133, 'Pacific Islands Scrub Forest/Shrub', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (134, 'Pacific Islands Swamp/Marsh', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (135, 'Pacific Islands Upland Forest', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (136, 'Peatland Forests', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (137, 'Periglacial Woodland and Shrubland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (138, 'Pine Flatwoods', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (139, 'Pine-Hemlock-Hardwood Forest', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (140, 'Pinyon-Juniper Woodland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (141, 'Pitch Pine Woodlands', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (142, 'Pocosin', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (143, 'Ponderosa Pine Forest, Woodland and Savanna', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (144, 'Post Oak Woodland and Savanna', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (145, 'Prairies and Barrens', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (146, 'Quarries-Strip Mines-Gravel Pits', 1);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (147, 'Red Alder Forest and Woodland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (148, 'Red Fir Forest and Woodland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (149, 'Red Pine-White Pine Forest and Woodland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (150, 'Redwood Forest and Woodland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (151, 'Riparian Stringer Forest and Shrubland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (152, 'Ruderal Forest', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (153, 'Salt Desert Scrub', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (154, 'Sand Prairie', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (155, 'Sand Shrubland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (156, 'Shortgrass Prairie', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (157, 'Shortleaf Pine Woodland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (158, 'Shortleaf Pine-Oak Forest and Woodland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (159, 'Shrub Swamp', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (160, 'Shrub Tundra', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (161, 'Shrub and Herbaceous Floodplain Wetland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (162, 'Shrub and Herbaceous Peatlands', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (163, 'Sitka Spruce Forest', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (164, 'Snow-Ice', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (165, 'Southern Scrub Oak', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (166, 'Sparse Shrub and Fell-field', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (167, 'Sparse Tundra', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (168, 'Sparse Vegetation', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (169, 'Spruce Flats and Barrens', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (170, 'Spruce-Fir Forest and Woodland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (171, 'Spruce-Fir-Hardwood Forest', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (172, 'Spruce-Lichen Woodland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (173, 'Subalpine Woodland and Parkland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (174, 'Succulent Desert Scrub', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (175, 'Sweetgum-Water Oak Forest', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (176, 'Tallgrass Prairie', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (177, 'Texas Live Oak', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (178, 'Tidal Flat', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (179, 'Tidal Marsh', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (180, 'Transitional Forest Vegetation', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (181, 'Transitional Herbacous Vegetation', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (182, 'Transitional Shrub Vegetation', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (183, 'Tussock Tundra', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (184, 'Virginia Pine Forest', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (185, 'Western Hemlock-Silver Fir Forest', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (186, 'Western Hemlock-Yellow-cedar Forest', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (187, 'Western Herbaceous Wetland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (188, 'Western Larch Forest and Woodland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (189, 'Western Oak Woodland and Savanna', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (190, 'Western Red-cedar-Western Hemlock Forest', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (191, 'Western Riparian Woodland and Shrubland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (192, 'Wet Meadow', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (193, 'White Oak-Beech Forest and Woodland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (194, 'White Oak-Red Oak-Hickory Forest and Woodland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (195, 'White Spruce Forest and Woodland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (196, 'White Spruce-Hardwood Forest and Woodland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (197, 'Willow Shrubland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (198, 'Yellow Birch-Sugar Maple Forest', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (199, 'Agricultural-Aquaculture', 0.66);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (200, 'Pinyon-Juniper Shrubland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (201, 'Developed-Wetland Mixed Forest', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (202, 'Developed-Wetland Herbaceous', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (203, 'Developed-Wetland Shrubland', 0);
INSERT INTO land_uses (land_use_id, name, intensity) VALUES (204, 'Quarries-Strip Mines-Gravel Pits-Well and Wind Pads', 0);