INSERT INTO ecoregions (ecoregion_id, name) VALUES (1, 'Coast Range');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (2, 'Puget Lowland');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (3, 'Willamette Valley');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (4, 'Cascades');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (5, 'Sierra Nevada');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (6, 'Central California Foothills and Coastal Mountains');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (7, 'Central California Valley');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (8, 'Southern California Mountains');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (9, 'Eastern Cascades Slopes and Foothills');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (10, 'Columbia Plateau');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (11, 'Blue Mountains');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (12, 'Snake River Plain');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (13, 'Central Basin and Range');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (14, 'Mojave Basin and Range');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (15, 'Northern Rockies');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (16, 'Idaho Batholith');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (17, 'Middle Rockies');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (18, 'Wyoming Basin');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (19, 'Wasatch and Uinta Mountains');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (20, 'Colorado Plateaus');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (21, 'Southern Rockies');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (22, 'Arizona/New Mexico Plateau');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (23, 'Arizona/New Mexico Mountains');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (24, 'Chihuahuan Deserts');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (25, 'High Plains');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (26, 'Southwestern Tablelands');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (27, 'Central Great Plains');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (28, 'Flint Hills');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (29, 'Cross Timbers');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (30, 'Edwards Plateau');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (31, 'Southern Texas Plains');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (32, 'Texas Blackland Prairies');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (33, 'East Central Texas Plains');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (34, 'Western Gulf Coastal Plain');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (35, 'South Central Plains');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (36, 'Ouachita Mountains');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (37, 'Arkansas Valley');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (38, 'Boston Mountains');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (39, 'Ozark Highlands');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (40, 'Central Irregular Plains');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (41, 'Canadian Rockies');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (42, 'Northwestern Glaciated Plains');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (43, 'Northwestern Great Plains');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (44, 'Nebraska Sand Hills');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (45, 'Piedmont');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (46, 'Northern Glaciated Plains');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (47, 'Western Corn Belt Plains');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (48, 'Lake Agassiz Plain');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (49, 'Northern Minnesota Wetlands');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (50, 'Northern Lakes and Forests');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (51, 'North Central Hardwood Forests');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (52, 'Driftless Area');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (53, 'Southeastern Wisconsin Till Plains');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (54, 'Central Corn Belt Plains');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (55, 'Eastern Corn Belt Plains');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (56, 'Southern Michigan/Northern Indiana Drift Plains');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (57, 'Huron/Erie Lake Plains');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (58, 'Northeastern Highlands');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (59, 'Northeastern Coastal Zone');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (60, 'Northern Allegheny Plateau');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (61, 'Erie Drift Plain');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (62, 'North Central Appalachians');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (63, 'Middle Atlantic Coastal Plain');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (64, 'Northern Piedmont');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (65, 'Southeastern Plains');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (66, 'Blue Ridge');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (67, 'Ridge and Valley');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (68, 'Southwestern Appalachians');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (69, 'Central Appalachians');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (70, 'Western Allegheny Plateau');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (71, 'Interior Plateau');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (72, 'Interior River Valleys and Hills');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (73, 'Mississippi Alluvial Plain');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (74, 'Mississippi Valley Loess Plains');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (75, 'Southern Coastal Plain');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (76, 'Southern Florida Coastal Plain');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (77, 'North Cascades');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (78, 'Klamath Mountains/California High North Coast Range');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (79, 'Madrean Archipelago');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (80, 'Northern Basin and Range');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (81, 'Sonoran Basin and Range');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (82, 'Acadian Plains and Hills');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (83, 'Eastern Great Lakes Lowlands');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (84, 'Atlantic Coastal Pine Barrens');
INSERT INTO ecoregions (ecoregion_id, name) VALUES (85, 'Southern California/Northern Baja Coast');