"""
Fetch column (field) metadata from an FGDC CSDGM metadata XML document and
produce a ``columns`` list conforming to the Riverscapes layer_definitions.json
schema.

Background
----------
ArcGIS publishes FGDC CSDGM metadata alongside each hosted item at a stable URL::

    https://www.arcgis.com/sharing/rest/content/items/{itemId}/info/metadata/metadata.xml

This XML contains rich field-level documentation under ``<eainfo>/<detailed>/<attr>``:

- ``<attrlabl>``   — field name
- ``<attrdef>``    — human-readable description
- ``<attrdefs>``   — source/authority for the definition
- ``<attrdomv>/<edom>``  — enumerated domain values (``<edomv>`` code,
  ``<edomvd>`` description, optionally ``<edomvds>`` source)
- ``<attrdomv>/<udom>``  — unrepresented domain (free-text description)

Dataset-level metadata (title, abstract, purpose, bounding box) is also
extracted and returned separately so callers can write it into a
layer_definitions header or run-log.

This module is complementary to ``fetch_fgdb_metadata.py`` (which reads field
types, aliases and coded-value domains directly from a downloaded .gdb) and
``fetch_arcgis_metadata.py`` (which uses the ArcGIS Hub REST API + feature
service).  Using all three together allows cross-checking and produces the
richest possible column definitions.

Comparison helper
-----------------
``compare_columns()`` accepts two column lists (e.g. one from the FGDB module
and one from this module) and prints a side-by-side diff showing:
- fields present in only one source
- differences in dtype, friendly_name, or description

Usage
-----
As a CLI (prints JSON to stdout)::

    python fetch_xml_metadata.py \\
        "https://www.arcgis.com/sharing/rest/content/items/6bf2e737c59d4111be92420ee5ab0b46/info/metadata/metadata.xml"

    # Or supply just the AGOL item ID — the URL is constructed automatically:
    python fetch_xml_metadata.py 6bf2e737c59d4111be92420ee5ab0b46

    # Emit dataset-level summary as well (to stderr):
    python fetch_xml_metadata.py <url_or_id> --show-dataset-info

    # Write directly into an existing layer_definitions.json:
    python fetch_xml_metadata.py <url_or_id> \\
        --layer-definitions layer_definitions.json \\
        --layer-id blm_ownership

    # Compare against FGDB-extracted columns (JSON file or via module):
    python fetch_xml_metadata.py <url_or_id> \\
        --compare-fgdb ~/GISData/SMA_WM.gdb SurfaceManagementAgency

As a library::

    from vector_prep.fetch_xml_metadata import (
        fetch_columns_from_xml_url,
        fetch_dataset_info_from_xml_url,
        compare_columns,
    )
    columns = fetch_columns_from_xml_url(
        "https://www.arcgis.com/sharing/rest/content/items/6bf2e737c59d4111be92420ee5ab0b46/info/metadata/metadata.xml"
    )
    info = fetch_dataset_info_from_xml_url(...)
"""

import argparse
import json
import re
import sys
import xml.etree.ElementTree as ET
from dataclasses import dataclass, field
from typing import Optional
from urllib.request import urlopen

import requests

# Fields auto-generated by ESRI that are rarely useful for schema documentation.
SYSTEM_FIELDS: set[str] = {
    "OBJECTID",
    "FID",
    "GlobalID",
    "Original_GlobalID",
    "Shape__Area",
    "Shape__Length",
    "Shape_Area",
    "Shape_Length",
    "SHAPE",
    "Shape",
    "created_user",
    "created_date",
    "last_edited_user",
    "last_edited_date",
}

AGOL_METADATA_URL_TEMPLATE = (
    "https://www.arcgis.com/sharing/rest/content/items/{item_id}"
    "/info/metadata/metadata.xml"
)


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------
@dataclass
class DatasetInfo:
    """Dataset-level metadata extracted from the FGDC XML."""

    title: str = ""
    abstract: str = ""
    purpose: str = ""
    pub_date: str = ""
    originator: str = ""
    west: Optional[float] = None
    east: Optional[float] = None
    north: Optional[float] = None
    south: Optional[float] = None
    keywords: list[str] = field(default_factory=list)
    update_frequency: str = ""
    entity_name: str = ""        # <enttypl> — the layer / entity name
    entity_description: str = "" # <enttypd>


# ---------------------------------------------------------------------------
# URL helpers
# ---------------------------------------------------------------------------
_ITEM_ID_RE = re.compile(r"^[0-9a-f]{32}$", re.IGNORECASE)


def _resolve_url(url_or_id: str) -> str:
    """Return a full metadata XML URL.

    Accepts either:
    - A 32-hex-char AGOL item ID  →  constructs the standard metadata URL.
    - Any other string            →  returned unchanged (assumed to be a URL).
    """
    if _ITEM_ID_RE.match(url_or_id.strip()):
        return AGOL_METADATA_URL_TEMPLATE.format(item_id=url_or_id.strip())
    return url_or_id


def _fetch_xml_root(url: str) -> ET.Element:
    """Fetch and parse the XML at *url*, returning the root element."""
    resp = requests.get(url, timeout=30)
    resp.raise_for_status()
    return ET.fromstring(resp.content)


# ---------------------------------------------------------------------------
# Dataset-level metadata
# ---------------------------------------------------------------------------
def _text(el: Optional[ET.Element]) -> str:
    """Return stripped text of *el*, or empty string if None or empty."""
    if el is None or not el.text:
        return ""
    return el.text.strip()


def _first(root: ET.Element, *paths: str) -> Optional[ET.Element]:
    """Return the first element matching any of the given ElementPath expressions."""
    for path in paths:
        el = root.find(path)
        if el is not None:
            return el
    return None


def parse_dataset_info(root: ET.Element) -> DatasetInfo:
    """Extract dataset-level metadata from the FGDC CSDGM XML root element."""
    info = DatasetInfo()

    # Title — ISO/FGDC hybrid as published by ArcGIS
    info.title = _text(_first(root,
        "idinfo/citation/citeinfo/title",  # classic FGDC
        "dataIdInfo/idCitation/resTitle",  # ISO profile used by ArcGIS
        ".//resTitle",
    ))

    # Abstract
    info.abstract = _text(_first(root,
        "idinfo/descript/abstract",
        "dataIdInfo/idAbs",
        ".//idAbs",
    ))

    # Purpose
    info.purpose = _text(_first(root,
        "idinfo/descript/purpose",
        "dataIdInfo/idPurp",
        ".//idPurp",
    ))

    # Publication date
    info.pub_date = _text(_first(root,
        "idinfo/citation/citeinfo/pubdate",
        ".//pubDate",
    ))

    # Originator / publisher
    info.originator = _text(_first(root,
        "idinfo/citation/citeinfo/origin",
        ".//rpIndName",
        ".//rpOrgName",
    ))

    # Bounding box
    bbox = _first(root,
        "idinfo/spdom/bounding",          # classic FGDC
        ".//GeoBndBox",                   # ISO/FGDC ArcGIS hybrid
    )
    if bbox is not None:
        try:
            info.west  = float(_text(bbox.find("westbc")  or bbox.find("westBL") ))
            info.east  = float(_text(bbox.find("eastbc")  or bbox.find("eastBL") ))
            info.north = float(_text(bbox.find("northbc") or bbox.find("northBL")))
            info.south = float(_text(bbox.find("southbc") or bbox.find("southBL")))
        except (TypeError, ValueError):
            pass

    # Keywords
    info.keywords = [
        kw.text.strip()
        for kw in root.iter("keyword")
        if kw.text and kw.text.strip()
    ]

    # Entity (layer) name and description
    enttyp = _first(root, ".//enttyp")
    if enttyp is not None:
        info.entity_name = _text(enttyp.find("enttypl"))
        info.entity_description = _text(enttyp.find("enttypd"))

    return info


# ---------------------------------------------------------------------------
# Field / attribute parsing
# ---------------------------------------------------------------------------
def _parse_edom_block(attrdomv_el: ET.Element) -> list[dict]:
    """Parse all <edom> children into a list of {code, description} dicts."""
    entries = []
    for edom in attrdomv_el.findall("edom"):
        code = _text(edom.find("edomv"))
        desc = _text(edom.find("edomvd"))
        if code:
            entries.append({"code": code, "description": desc})
    return entries


def _build_domain_description(entries: list[dict]) -> str:
    """Format enumerated domain entries as a compact string."""
    return "; ".join(
        f"{e['code']}={e['description']}" if e["description"] else e["code"]
        for e in entries
    )


def parse_field_attrs(root: ET.Element, include_system_fields: bool = False) -> list[dict]:
    """Extract field-level metadata from ``<eainfo>/<detailed>/<attr>`` elements.

    Returns a list of column dicts conforming to the layer_definitions schema:
    ``name``, optionally ``friendly_name``, ``dtype`` (always "STRING" — the XML
    does not carry type info), and optionally ``description``.

    Note: FGDC XML does not contain field data types; those must come from the
    FGDB or Feature Service.  The returned ``dtype`` is set to ``"STRING"`` as a
    placeholder and should be merged/overridden from a typed source.
    """
    columns: list[dict] = []

    for detailed in root.iter("detailed"):
        for attr in detailed.findall("attr"):
            name = _text(attr.find("attrlabl"))
            if not name:
                continue
            if not include_system_fields and name in SYSTEM_FIELDS:
                continue

            col: dict = {"name": name, "dtype": "STRING"}

            # Description from <attrdef>
            description = _text(attr.find("attrdef"))

            # Append enumerated domain values if present
            domain_parts: list[str] = []
            for attrdomv in attr.findall("attrdomv"):
                edom_entries = _parse_edom_block(attrdomv)
                if edom_entries:
                    domain_str = _build_domain_description(edom_entries)
                    domain_parts.append(f"Values: {domain_str}")
                else:
                    udom = _text(attrdomv.find("udom"))
                    if udom:
                        domain_parts.append(udom)

            if description and domain_parts:
                col["description"] = description + " " + " ".join(domain_parts)
            elif description:
                col["description"] = description
            elif domain_parts:
                col["description"] = " ".join(domain_parts)

            columns.append(col)

    return columns


# ---------------------------------------------------------------------------
# Top-level fetch functions
# ---------------------------------------------------------------------------
def fetch_columns_from_xml_url(
    url_or_id: str,
    include_system_fields: bool = False,
) -> list[dict]:
    """Fetch column definitions from an FGDC CSDGM XML URL or AGOL item ID.

    Args:
        url_or_id: Either a full metadata XML URL or a 32-char AGOL item ID.
        include_system_fields: If True, include system-generated fields such as
            ``OBJECTID``, ``Shape_Length``, etc.

    Returns:
        A list of column dicts (name, dtype placeholder, optional description).
        ``dtype`` is always ``"STRING"`` — merge with typed source (FGDB or
        Feature Service) to get accurate types.
    """
    url = _resolve_url(url_or_id)
    root = _fetch_xml_root(url)
    return parse_field_attrs(root, include_system_fields=include_system_fields)


def fetch_dataset_info_from_xml_url(url_or_id: str) -> DatasetInfo:
    """Fetch dataset-level metadata from an FGDC CSDGM XML URL or AGOL item ID."""
    url = _resolve_url(url_or_id)
    root = _fetch_xml_root(url)
    return parse_dataset_info(root)


# ---------------------------------------------------------------------------
# Column merge: XML descriptions → typed FGDB columns
# ---------------------------------------------------------------------------
def merge_xml_descriptions_into_fgdb_columns(
    fgdb_columns: list[dict],
    xml_columns: list[dict],
) -> list[dict]:
    """Overlay XML field descriptions onto FGDB-sourced column definitions.

    The FGDB columns carry accurate ``dtype``, ``friendly_name``, and domain
    info from coded-value domains.  The XML carries richer human-readable
    descriptions.  This function adds XML descriptions where the FGDB column
    has none, and appends XML descriptions in parentheses where the FGDB
    already has a domain-derived description.

    Returns a new list (does not mutate inputs).
    """
    xml_by_name = {col["name"]: col for col in xml_columns}
    merged = []
    for col in fgdb_columns:
        new_col = dict(col)
        xml_col = xml_by_name.get(col["name"])
        if xml_col:
            xml_desc = xml_col.get("description", "")
            existing_desc = new_col.get("description", "")
            if xml_desc and not existing_desc:
                new_col["description"] = xml_desc
            elif xml_desc and existing_desc and xml_desc not in existing_desc:
                new_col["description"] = f"{existing_desc} ({xml_desc})"
        merged.append(new_col)
    return merged


# ---------------------------------------------------------------------------
# Comparison helper
# ---------------------------------------------------------------------------
def compare_columns(
    columns_a: list[dict],
    columns_b: list[dict],
    label_a: str = "source_a",
    label_b: str = "source_b",
) -> dict:
    """Compare two column lists and return a structured diff.

    Returns:
        A dict with keys:
        - ``only_in_a``   — list of field names only in *columns_a*
        - ``only_in_b``   — list of field names only in *columns_b*
        - ``differences`` — list of {name, field, a_value, b_value} dicts for
          fields present in both but with differing values (dtype, description,
          friendly_name)
        - ``matching``    — count of fields that match completely
    """
    a_by_name = {c["name"]: c for c in columns_a}
    b_by_name = {c["name"]: c for c in columns_b}

    only_a = sorted(set(a_by_name) - set(b_by_name))
    only_b = sorted(set(b_by_name) - set(a_by_name))

    differences = []
    matching = 0
    for name in sorted(set(a_by_name) & set(b_by_name)):
        ca = a_by_name[name]
        cb = b_by_name[name]
        diffs_for_field = []
        for key in ("dtype", "friendly_name", "description"):
            va = ca.get(key, "")
            vb = cb.get(key, "")
            if va != vb:
                diffs_for_field.append({
                    "field": key,
                    f"{label_a}": va,
                    f"{label_b}": vb,
                })
        if diffs_for_field:
            differences.append({"name": name, "diffs": diffs_for_field})
        else:
            matching += 1

    return {
        f"only_in_{label_a}": only_a,
        f"only_in_{label_b}": only_b,
        "differences": differences,
        "matching": matching,
    }


# ---------------------------------------------------------------------------
# Optional: patch an existing layer_definitions.json
# ---------------------------------------------------------------------------
def update_layer_definitions(path: str, layer_id: str, columns: list[dict]) -> None:
    """Replace the ``columns`` array of a specific layer in layer_definitions.json."""
    with open(path, "r", encoding="utf-8") as fh:
        doc = json.load(fh)
    for layer in doc.get("layers", []):
        if layer.get("layer_id") == layer_id:
            layer["columns"] = columns
            break
    else:
        raise LookupError(f"layer_id '{layer_id}' not found in {path}")
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(doc, fh, indent=4, ensure_ascii=False)
        fh.write("\n")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Extract column metadata from an FGDC CSDGM metadata XML document "
            "(ArcGIS item metadata URL or AGOL item ID)."
        )
    )
    parser.add_argument(
        "url_or_id",
        help=(
            "Full metadata XML URL or a 32-char AGOL item ID. "
            "Example item ID: 6bf2e737c59d4111be92420ee5ab0b46"
        ),
    )
    parser.add_argument(
        "--show-dataset-info",
        action="store_true",
        help="Print dataset-level metadata summary to stderr.",
    )
    parser.add_argument(
        "--include-system-fields",
        action="store_true",
        help="Include OBJECTID, Shape_Length, etc.",
    )
    parser.add_argument(
        "--layer-definitions",
        help="Path to an existing layer_definitions.json to update in-place.",
    )
    parser.add_argument(
        "--layer-id",
        help="layer_id within layer_definitions.json to update (required with --layer-definitions).",
    )
    parser.add_argument(
        "--compare-fgdb",
        nargs=2,
        metavar=("GDB_PATH", "LAYER_NAME"),
        help=(
            "Compare XML-derived columns against columns read directly from "
            "a File Geodatabase.  Prints a diff report to stdout instead of "
            "the column list."
        ),
    )
    args = parser.parse_args()

    if args.layer_definitions and not args.layer_id:
        parser.error("--layer-id is required when --layer-definitions is specified.")

    if args.show_dataset_info:
        info = fetch_dataset_info_from_xml_url(args.url_or_id)
        print("=== Dataset Info ===", file=sys.stderr)
        print(f"  Title       : {info.title}", file=sys.stderr)
        print(f"  Pub date    : {info.pub_date}", file=sys.stderr)
        print(f"  Originator  : {info.originator}", file=sys.stderr)
        print(f"  Entity      : {info.entity_name} — {info.entity_description}", file=sys.stderr)
        if info.west is not None:
            print(
                f"  Bounding box: W={info.west} E={info.east} "
                f"N={info.north} S={info.south}",
                file=sys.stderr,
            )
        if info.keywords:
            print(f"  Keywords    : {', '.join(info.keywords[:10])}", file=sys.stderr)
        print(f"  Abstract    : {info.abstract[:200]}...", file=sys.stderr)
        print("", file=sys.stderr)

    xml_columns = fetch_columns_from_xml_url(
        args.url_or_id,
        include_system_fields=args.include_system_fields,
    )

    if args.compare_fgdb:
        # Import here to avoid hard dependency when not comparing
        from vector_prep.fetch_fgdb_metadata import fetch_columns_from_fgdb  # noqa: PLC0415

        gdb_path, layer_name = args.compare_fgdb
        fgdb_columns = fetch_columns_from_fgdb(
            gdb_path,
            layer_name,
            include_system_fields=args.include_system_fields,
        )
        diff = compare_columns(fgdb_columns, xml_columns, label_a="fgdb", label_b="xml")
        json.dump(diff, sys.stdout, indent=2)
        sys.stdout.write("\n")
        # Also print summary to stderr
        print(
            f"\nSummary: {diff['matching']} fields match, "
            f"{len(diff['differences'])} differ, "
            f"{len(diff.get('only_in_fgdb', []))} only in FGDB, "
            f"{len(diff.get('only_in_xml', []))} only in XML.",
            file=sys.stderr,
        )
        return

    if args.layer_definitions:
        update_layer_definitions(args.layer_definitions, args.layer_id, xml_columns)
        print(
            f"Updated {args.layer_definitions} layer '{args.layer_id}' "
            f"with {len(xml_columns)} columns.",
            file=sys.stderr,
        )
    else:
        json.dump(xml_columns, sys.stdout, indent=4, ensure_ascii=False)
        sys.stdout.write("\n")


if __name__ == "__main__":
    main()
