"""
Fetch column (field) metadata from an ESRI File Geodatabase (FGDB) and produce
a ``columns`` list conforming to the Riverscapes layer_definitions.json schema.

Background
----------
ESRI File Geodatabases store rich schema metadata inside the .gdb directory
that GDAL's OpenFileGDB driver can read:

- **Field aliases** (``GetAlternativeName()``) — human-readable names for the
  truncated column names (e.g. ``hydroseq`` → ``HydrologicSequence``).
- **Coded-value domains** — lookup tables that map integer/string codes to
  descriptive labels (e.g. ``Resolution``: 1=Local, 2=High, 3=Medium).
- **Field type** — mapped to the layer_definitions dtype enum.

This is the FGDB equivalent of ``fetch_arcgis_metadata.py`` (which scrapes
ArcGIS Hub Feature Service REST APIs). Use this module when the source data
is a downloaded FileGDB rather than a live service — e.g. the USGS NHDPlus HR
from ScienceBase.

Usage
-----
As a CLI (prints JSON to stdout)::

    python fetch_fgdb_metadata.py /path/to/data.gdb NetworkNHDFlowline

To write directly into an existing layer_definitions.json layer entry::

    python fetch_fgdb_metadata.py /path/to/data.gdb NetworkNHDFlowline \\
        --layer-definitions layer_definitions.json \\
        --layer-id usgs-nhdplushr-network-flowline

As a library::

    from fetch_fgdb_metadata import fetch_columns_from_fgdb
    columns = fetch_columns_from_fgdb("/path/to/data.gdb", "NetworkNHDFlowline")
"""

import argparse
import json
import sys

from osgeo import ogr

# ---------------------------------------------------------------------------
# OGR field-type → layer_definitions.json dtype mapping
# ---------------------------------------------------------------------------
OGR_TYPE_MAP: dict[int, str] = {
    ogr.OFTString: "STRING",
    ogr.OFTInteger: "INTEGER",
    ogr.OFTInteger64: "INTEGER",
    ogr.OFTReal: "FLOAT",
    ogr.OFTDate: "DATETIME",
    ogr.OFTDateTime: "DATETIME",
    ogr.OFTTime: "DATETIME",
}

# Fields auto-generated by ESRI / GDAL that are not meaningful for schema docs.
SYSTEM_FIELDS: set[str] = {
    "OBJECTID",
    "FID",
    "GlobalID",
    "Shape",
    "Shape_Length",
    "Shape_Area",
    "Shape__Area",
    "Shape__Length",
}


# ---------------------------------------------------------------------------
# Domain helpers
# ---------------------------------------------------------------------------
def _fetch_domain_descriptions(ds) -> dict[str, dict]:
    """Return {domain_name: {code: label, ...}} for all coded-value domains.

    Only coded-value domains (OFDT_CODED) are included; range domains are
    skipped since they do not have enumerated labels.
    """
    domains: dict[str, dict] = {}
    try:
        domain_names = ds.GetFieldDomainNames()
    except Exception:
        return domains

    if not domain_names:
        return domains

    for name in domain_names:
        dom = ds.GetFieldDomain(name)
        if dom is None:
            continue
        if dom.GetDomainType() == ogr.OFDT_CODED:
            enum = dom.GetEnumeration()
            if enum:
                domains[name] = dict(enum)
    return domains


def _format_domain_description(domain_name: str, code_map: dict) -> str:
    """Build a human-readable description suffix from a coded-value domain.

    Example output: "Domain 'Resolution': 1=Local, 2=High, 3=Medium"
    """
    pairs = ", ".join(f"{k}={v}" for k, v in code_map.items())
    return f"Domain '{domain_name}': {pairs}"


# ---------------------------------------------------------------------------
# Core: build columns list from a single FGDB layer
# ---------------------------------------------------------------------------
def fetch_columns_from_fgdb(
    gdb_path: str,
    layer_name: str,
    include_system_fields: bool = False,
    include_domains_in_description: bool = True,
) -> list[dict]:
    """Extract column definitions from an FGDB layer.

    Args:
        gdb_path: Path to the .gdb directory.
        layer_name: Name of the layer/table inside the GDB.
        include_system_fields: If True, include OBJECTID, Shape_Length, etc.
        include_domains_in_description: If True, append coded-value domain
            mappings to the description string.

    Returns:
        A list of column dicts ready for layer_definitions.json ``columns``.
    """
    ds = ogr.Open(gdb_path, 0)
    if ds is None:
        raise FileNotFoundError(f"Cannot open GDB: {gdb_path}")

    lyr = ds.GetLayerByName(layer_name)
    if lyr is None:
        available = [ds.GetLayer(i).GetName() for i in range(ds.GetLayerCount())]
        raise LookupError(
            f"Layer '{layer_name}' not found in {gdb_path}. "
            f"Available: {available}"
        )

    # Pre-load all coded-value domains from the dataset
    all_domains = _fetch_domain_descriptions(ds)

    defn = lyr.GetLayerDefn()
    columns: list[dict] = []

    for i in range(defn.GetFieldCount()):
        fd = defn.GetFieldDefn(i)
        name = fd.GetName()

        if not include_system_fields and name in SYSTEM_FIELDS:
            continue

        ogr_type = fd.GetType()
        dtype = OGR_TYPE_MAP.get(ogr_type, "STRING")

        col: dict = {"name": name}

        # friendly_name from FGDB field alias
        alias = fd.GetAlternativeName() or ""
        if alias and alias != name:
            col["friendly_name"] = alias

        col["dtype"] = dtype

        # Build description from domain if present
        domain_name = fd.GetDomainName() or ""
        description_parts: list[str] = []
        if domain_name and include_domains_in_description:
            code_map = all_domains.get(domain_name)
            if code_map:
                description_parts.append(_format_domain_description(domain_name, code_map))
            else:
                description_parts.append(f"Domain: {domain_name}")

        if description_parts:
            col["description"] = "; ".join(description_parts)

        columns.append(col)

    ds = None  # close
    return columns


def fetch_all_layer_names(gdb_path: str) -> list[dict]:
    """Return a summary of every layer in the GDB.

    Each entry has keys: name, geometry_type, feature_count.
    """
    ds = ogr.Open(gdb_path, 0)
    if ds is None:
        raise FileNotFoundError(f"Cannot open GDB: {gdb_path}")

    layers = []
    for i in range(ds.GetLayerCount()):
        lyr = ds.GetLayer(i)
        geom_type = ogr.GeometryTypeToName(lyr.GetGeomType()) if lyr.GetGeomType() != ogr.wkbNone else "None"
        layers.append({
            "name": lyr.GetName(),
            "geometry_type": geom_type,
            "feature_count": lyr.GetFeatureCount(),
        })
    ds = None
    return layers


# ---------------------------------------------------------------------------
# Optional: patch an existing layer_definitions.json (same as arcgis version)
# ---------------------------------------------------------------------------
def update_layer_definitions(path: str, layer_id: str, columns: list[dict]) -> None:
    """Replace the ``columns`` array of a specific layer in a layer_definitions.json file."""
    with open(path, "r", encoding="utf-8") as fh:
        doc = json.load(fh)

    for layer in doc.get("layers", []):
        if layer.get("layer_id") == layer_id:
            layer["columns"] = columns
            break
    else:
        raise LookupError(f"layer_id '{layer_id}' not found in {path}")

    with open(path, "w", encoding="utf-8") as fh:
        json.dump(doc, fh, indent=4, ensure_ascii=False)
        fh.write("\n")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def main() -> None:
    parser = argparse.ArgumentParser(
        description="Extract column metadata from an ESRI File Geodatabase layer."
    )
    parser.add_argument("gdb_path", help="Path to the .gdb directory")
    parser.add_argument("layer_name", help="Layer or table name inside the GDB")
    parser.add_argument(
        "--layer-definitions",
        help="Path to layer_definitions.json to update in-place",
    )
    parser.add_argument(
        "--layer-id",
        help="layer_id to update in layer_definitions.json (required with --layer-definitions)",
    )
    parser.add_argument(
        "--include-system-fields",
        action="store_true",
        help="Include OBJECTID, Shape_Length, etc.",
    )
    parser.add_argument(
        "--list-layers",
        action="store_true",
        help="List all layers in the GDB and exit",
    )

    args = parser.parse_args()

    if args.list_layers:
        layers = fetch_all_layer_names(args.gdb_path)
        for lyr in layers:
            print(f"  {lyr['name']:30s}  {lyr['geometry_type']:30s}  {lyr['feature_count']:>12,}")
        return

    columns = fetch_columns_from_fgdb(
        args.gdb_path,
        args.layer_name,
        include_system_fields=args.include_system_fields,
    )

    if args.layer_definitions:
        if not args.layer_id:
            parser.error("--layer-id is required when --layer-definitions is specified")
        update_layer_definitions(args.layer_definitions, args.layer_id, columns)
        print(f"Updated {args.layer_id} with {len(columns)} columns in {args.layer_definitions}")
    else:
        json.dump(columns, sys.stdout, indent=2, ensure_ascii=False)
        print()


if __name__ == "__main__":
    main()
